FROM nginx:alpine

COPY /dist /usr/share/nginx/html/
#COPY /glammy_full_noimage /usr/share/nginx/html/
#docker run --rm -d --name nginx -p 80:80 -v c:/mywebsites/hatun:/usr/share/nginx/html nginx:alpine
#docker run --rm -d --name nginx -p 80:80 -v /home/iquitos_silva/angular-material/main/dist:/usr/share/nginx/html nginx:alpine
EXPOSE 80
